name = "wompbat"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "ccpm-megatable"
# Replace with real database_id after: tofu apply (or: wrangler d1 create ccpm-megatable)
database_id = "b69fe0fa-d6d5-4278-91db-9666889960c6"
preview_database_id = "DB"
